pages:
  only:
  - master
  image: hub.cloud.ctripcorp.com/devops/centos7.2-nodejs10.15.1-npm6.4.1:latest
  before_script:
    - yum -y install git
  script:
    - npm install
  artifacts:
    paths:
    - public
